# Generated by Django 5.0.1 on 2024-02-06 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cateogary',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='cateogaryName',
            new_name='categoryName',
        ),
        migrations.RenameField(
            model_name='listings',
            old_name='cateogary',
            new_name='category',
        ),
    ]
