# Generated by Django 5.0.1 on 2024-02-07 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_rename_description_listings_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='description',
            field=models.CharField(max_length=600),
        ),
    ]
